export const TASK_PRIORITY = Object.freeze({
	LOW: "LOW",
	MEDIUM: "MEDIUM",
	HIGH: "HIGH",
	URGENT: "URGENT",
});

export const TASK_STATUS = Object.freeze({
	TODO: "TODO",
	IN_PROGRESS: "IN_PROGRESS",
	REVIEW: "REVIEW",
	DONE: "DONE",
});

export const PROJECT_STATUS = Object.freeze({
	ACTIVE: "ACTIVE",
	ON_HOLD: "ON_HOLD",
	COMPLETED: "COMPLETED",
	CANCELLED: "CANCELLED",
});

export const PROJECT_ROLE = Object.freeze({
	OWNER: "OWNER",
	ADMIN: "ADMIN",
	MEMBER: "MEMBER",
	VIEWER: "VIEWER",
});

export const NOTIFICATION_TYPE = Object.freeze({
	TASK_ASSIGNED: "TASK_ASSIGNED",
	TASK_UPDATED: "TASK_UPDATED",
	TASK_COMPLETED: "TASK_COMPLETED",
	PROJECT_INVITED: "PROJECT_INVITED",
	PROJECT_UPDATED: "PROJECT_UPDATED",
	COMMENT_ADDED: "COMMENT_ADDED",
	MENTIONED: "MENTIONED",
});

export const USER_ROLE = Object.freeze({
	ADMIN: "ADMIN",
	USER: "USER",
});

export const GROUP_ROLE = Object.freeze({
	ADMIN: "ADMIN",
	MEMBER: "MEMBER",
});

export const AUTH_STATUS = Object.freeze({
	PENDING: "PENDING",
	VERIFIED: "VERIFIED",
	BLOCKED: "BLOCKED",
});
